name: Trigger Site Rebuild on a CRON Schedule

on:
  schedule:
    - cron: '0 * * * *'
jobs:
  build:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: curl -X POST -d {} https://api.vercel.com/v1/integrations/deploy/prj_SVGYAQlXJtkFPIUaPzsolxHIyyG0/5nJEo1bwW2
